### ISSUE TITLE
Possibility with locked Versizon/ATT Galaxy S5 Bootloader?

### ISSUE THREAD

**Issue by selbyk** [djrbliss/loki#85]
@djrbliss, this looks like fun and am on a mission to root my ATT S5 and wanted to know if you think it's even worth attempting.  How different do you think the process would be from S4 to S5 in terms of code adaption?

Looking at the adb shell commands, this is requires root if you can't flash bl or recovery images, huh?  About all I can do is flash a kernel with Odin and fastboot seems impossible to use.  

Rooting this S5 has been a nightmare.  This isn't the first C code I've had to compile and modify on this journey (Heimdall b4 breaking down and running Windows 7 in Virtualbox). I'm pretty set on trying everything I can to eventually root this machine. Think it's even going to be possible?

**Comment by selbyk** [comment]
Got Heimdall working but I couldn't figure out how to use it since anyone hardly knows what it is. I haven't even seen the community as a whole define the options on Odin, and it was less work with most of the roms and images I found anyway.*

**Comment by djrbliss** [comment]
@selbyk Loki has never supported the Samsung Galaxy S5, since the vulnerability Loki exploits was patched prior to its release. Loki also has nothing to do with rooting a device. Instead, it allows flashing custom boot (kernel/ramdisk) or recovery images on supported devices with otherwise locked bootloaders, which requires root access.

I honestly have no idea how easy it would be to root you Galaxy S5. First check if any public exploits are available for use. If not, then unless you have some experience with vulnerability research and exploit development, you're probably out of luck.
